child(andrew,elizabeth).
child(andrew,philip).
child(anne,elizabeth).
child(anne,philip).
child(beatrice,andrew).
child(beatrice,sarah).
child(charles,elizabeth).
child(charles,philip).
child(diana,kydd).
child(diana,spencer).
child(edward,elizabeth).
child(edward,philip).
child(elizabeth,george).
child(elizabeth,mum).
child(eugenie,andrew).
child(eugenie,sarah).
child(harry,charles).
child(harry,diana).
child(james,edward).
child(james,sophie).
child(louise,edward).
child(louise,sophie).
child(margaret,george).
child(margaret,mum).
child(peter,anne).
child(peter,mark).
child(william,charles).
child(william,diana).
child(zara,anne).
child(zara,mark).

female(anne).
female(beatrice).
female(diana).
female(elizabeth).
female(kydd).
female(louise).
female(margaret).
female(mum).
female(sarah).
female(sophie).
female(zara).

male(andrew).
male(charles).
male(edward).
male(eugenie).
male(george).
male(harry).
male(james).
male(mark).
male(peter).
male(philip).
male(spencer).
male(william).

spouse(anne,mark).
spouse(diana,charles).
spouse(elizabeth,philip).
spouse(kydd,spencer).
spouse(mum,george).
spouse(sarah,andrew).
spouse(sophie,edward).

